services:
  workflow:
    build: ./workflow
    depends_on:
      - usersdb
      - taskdb
    environment:
      WORKFLOW_PORT: "8080"
      USERS_DB_URL: postgres://postgres:postgres@usersdb:5432/users?sslmode=disable
      TASKS_DB_URL: postgres://postgres:postgres@taskdb:5432/tasks?sslmode=disable
    ports:
      - "8080:8080"
  

  usersdb:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - pgdata_users:/var/lib/postgresql/data

  taskdb:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tasks
    ports:
      - "5431:5432"
    volumes:
      - pgdata_tasks:/var/lib/postgresql/data

volumes:
  pgdata_users:
  pgdata_tasks: